


const pickupData = {
    Nairobi_CBD : ["MOI AVENUE"],
    Nairobi_Metropolitan : ["SOUTH B", "SOUTH C", "IMARA DAIMA", "KITENGELA", "LANGATA", "KAREN", "KILIMANI", "LAVINGTON", "KILELESHWA", "PANGANI", "NGARA", "THIKA ROAD", "RUAKA", "WAIYAKI WAY", "NGONG TOWN", "SYOKIMAU", "MLOLONGO", "KIAMBU ROAD", "RONGAI", "KISERIAN", "EASTLEIGH", "WANYEE ROAD", "KAWANGWARE", "JERICHO", "KOMAROCK", "KAYOLE", "NGUMO", "HIGHRISE", "UMOJA", "BURUBURU", "EMBAKASI", "NYAYO ESTATE"],
    Other_Counties : ["NAKURU", "NYERI", "THIKA", "MACHAKOS", "MOMBASA", "KILIFI", "MAUA", "KISUMU", "BUNGOMA", "HOMABAY", "KAKAMEGA", "KITALE", "ELDORET", "KISII", "RONGO", "KAPSABET", "KABARNET", "NANYUKI"]
}

export default pickupData